### ISSUE TITLE
I forked your project and added/edited some things, you should check it out

### ISSUE THREAD

**Issue by puluceno** [jcoker85/NeweggScraper#2]
github.com/puluceno/scraper

**Comment by jcoker85** [comment]
Nice! Glad to see some necessary improvements being made. This was a real quick exercise for me just to get something working but glad to see you have added multithreading as it is needed when you start scraping more than 1 or 2 things. 

Adding the price support alone pretty much doubled the execution time due to what I assume is bad optimization in the HTML scraping on my part, but it's still within what I would consider acceptable timing (~10 sec per check on my machine), so I didn't spend too much time on it... especially since I managed to snag a 3090 a week or so ago. Now I see why everyone is looking for the Ryzen 5! 

I will keep an eye on your fork, I hope you get the view updating properly soon!

Thanks for your interest!

**Comment by puluceno** [comment]
That's awesome that you were able to get a 3090 man!
I was able to get the cpu by using "our" scraping tool.

I added more features, which includes automatic buying from Newegg in case
something comes into stock. All you need is to have your account ready with
delivery address and credit card info, and enter your login info on the app
(for now it is still hardcoded, if I have time maybe I will make it read
from the interface).

Also, the app is now multithreading by store (don't want to risk having my
ip blacklisted by "dos" them), and it is fully multithread by "item in
stock", opening one instance of the browser for each item in stock

The new app is available at https://github.com/puluceno/buybot in case you
want to check it out!
